### ISSUE TITLE
[Fix] How to Ensure Bots will not auto stop in Stealth.

### ISSUE THREAD

**Issue by hegyak** [Crackdown-PD2/BigLobby3#42]
You need to edit the Following LUA File:
lua\_custom\menu.lua

Change the Line:
	self._data.auto_stop_all_bots   = self._data.auto_stop_all_bots or true
To
	self._data.auto_stop_all_bots   = self._data.auto_stop_all_bots
		
Then change the line:
local allow = ( item:value() == "on" and true or false )
To
local allow = ( item:value() == "on" and true)

**Comment by steam-test1** [comment]
Fixed in the latest release

**Comment by Shad0wlife** [comment]
There was a reason this option existed. Bots used to jump through window in stealth because there was no stealth pathing (in vanilla they stay at spawn). The broken windows would of course alert guards.
I hope this issue is still removed. Otherwise moving bots in stealth judt will break stealth again.

**Comment by steam-test1** [comment]
It was causing crashes so it was removed, but the keybind is still available to use
I tried to fix it, but gave up
